version: "3.9"

volumes:
  PostgresData:

networks:
  pbgapi:

services:
  api:
    build: ./
    container_name: pbg-api
    depends_on:
      - db
    networks:
      - pbgapi
    env_file: ./.env
    ports:
      - "5000:5000"
    command: npm start  
  db:
    restart: unless-stopped
    image: postgres
    container_name: pbg-db
    networks:
      - pbgapi
    ports:
      - "5432"
    env_file: ./.env
    volumes:
      - PostgresData:/var/lib/postgresql/data  