version: "3.9"

services:
  pbg-api:
    build:
      context: ./
      args:
        DATABASE_URL: ${DATABASE_URL} 
    container_name: pbg-api
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    env_file: ./.env.dev
    ports:
      - 5000:5000
    command: npm run dev