version: "3.9"



services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: pbg-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - pbgapi
    ports:
      - "5432"
    volumes:
      - PostgresData:/var/lib/postgresql/data  
  api:
    build:
      context: ./
      args:
        DATABASE_URL: ${DATABASE_URL}
        PORT: ${PORT}
    container_name: pbg-api
    depends_on:
      - db
    networks:
      - pbgapi
    ports:
      - "5000:5000"
    command: npm start  
volumes:
  PostgresData:

networks:
  pbgapi:  